default_stages: [commit, push]
default_language_version:
  python: python3.9
repos:
   - repo: https://gitlab.com/pycqa/flake8
     rev: 3.9.2
     hooks:
      - id: flake8
        language: system
        types: [python]
        args: ["--max-line-length=120", "--ignore=E203,E266,E501,W503,F403,F401"]
        name: flake8
        entry: flake8
   - repo: https://github.com/psf/black
     rev: 22.3.0
     hooks:
      - id: black
        name: black
        language: python
        entry: black
        args: ["--line-length=120", "--skip-magic-trailing-comma"]
        exclude: |
          (?x)^(
              .flake8|
              (.*\.yaml)|
              (.*\.yml)|
              (.*\.txt)|
              (.*\.toml)|
              (.*\.ini)|
              (.*\.md)|
              (.*\.gitignore)|
              (.*\Dockerfile)|
              (.*\Dockerfile-report)|
          )$
        additional_dependencies: ["click==8.0.4"]
   - repo: https://github.com/PyCQA/isort
     rev: 5.10.1
     hooks:
      - id: isort
        args: ["--profile=black", "--line-length=120"]
        name: isort
        language: python
        entry: isort
   - repo: https://github.com/pre-commit/mirrors-mypy
     rev: 'v0.961'
     hooks:
      - id: mypy
        name: mypy
        language: system
        entry: mypy tests test_framework test_data
        args: ["--ignore-missing-imports"]
        pass_filenames: false